### ISSUE TITLE
Info prints are in the wrong order

### ISSUE THREAD

**Issue by Derpius** [Andrew-Eathan/aewebsocketcore#1]
Every status print to say a function has been "added", is actually **before** the function is even declared, simply cutting and pasting these prints that say functions have been added to after they're **actually** added would fix this.  
You also seem to use two different formats for these prints, `added <function name>!`, and `| <function name> |`.  

**Edit:** Some functions do not even have prints.  

(also you should at least use the default issue templates GitHub provides)

**Comment by Andrew-Eathan** [comment]
k

**Comment by Andrew-Eathan** [comment]
#b695117
done

**Comment by Andrew-Eathan** [comment]
a921187
fixed
